### ISSUE TITLE
Please attribute Sushi bucket

### ISSUE THREAD

**Issue by kidonng** [integzz/scoopet#3]
Hi, I just noticed you starred my bucket [Sushi](https://github.com/kidonng/sushi), so I went to browse your projects. I appreciate that you have created a great bucket as well, however I noticed some manifests (such as obsidian and microsoft-edge) are possibly from my bucket but there is no attribution. 
Please note Sushi is MIT licensed, which means you must include the license to use the code. In practice, you only have to attribute the projects you are using, which can be put anywhere as long as it is easy to find.

**Comment by integzz** [comment]
Sorry for the delayed response, I do not check this bucket often. I did not get the email since I un-watched this repo. Yes, I borrowed 3 manifests from `Sushi`, which are `tencent-meeting`, `obsidian` and `microsoft-edge`. I did not notice the licence issue. So thank you for informing, I will mention the source of these manifests and include the MIT licence.

**Comment by kidonng** [comment]
Thanks for the attribution! I don't mind the delayed response.
Just for your information, you don't have to **change** this repository's license to MIT (that's not what I'm asking for). As I mentioned above, leaving a link to where the manifest comes from is enough. Ignore this if it's your intention.

**Comment by integzz** [comment]
I just found that I skipped the conjunction `which`. It doesn't matter, I happen to need to get knowledge of these licences.
